moneybags/config/routes.rb
Moneybags::Application.routes.draw do
  resources :spaces

  root :to => 'welcome#index'

end

moneybags/app/models/space.rb
class Space < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :cost
  attr_accessible :name, :cost, :occupied
end

moneybags/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

moneybags/app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spaces }
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @space = Space.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/new
  # GET /spaces/new.json
  def new
    @space = Space.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/1/edit
  def edit
    @space = Space.find(params[:id])
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(params[:space])

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render json: @space, status: :created, location: @space }
      else
        format.html { render action: "new" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spaces/1
  # PUT /spaces/1.json
  def update
    @space = Space.find(params[:id])

    respond_to do |format|
      if @space.update_attributes(params[:space])
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space = Space.find(params[:id])
    @space.destroy

    respond_to do |format|
      format.html { redirect_to spaces_url }
      format.json { head :no_content }
    end
  end
end

moneybags/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@name = "Me"
		@spaces = Space.all
	end
end

moneybags/app/helpers/application_helper.rb
module ApplicationHelper
end

moneybags/app/helpers/spaces_helper.rb
module SpacesHelper
end

moneybags/app/views/Welcome/index.html.erb
<div id="main">
	<header>
		<h2>Robber Baron</h2>
		<h1>Mr. Monopoly</h1>
		<h2>Boardgame Legend</h2>
	</header>

	<p>Rich "Uncle" Pennybags is the round old man in a top hat who serves as the mascot of the game Monopoly. Unsuccessful attempts to rechristen Rich "Uncle" Pennybags as <a href="http://en.wikipedia.org/wiki/Rich_Uncle_Pennybags" target="_blank" title="Wikipedia page!">Mr. Monopoly</a> are periodically made, though most people refer to him that way. He also appears in the related games Advance to Boardwalk, Free Parking, Don't Go to Jail, Monopoly City, Monopoly Junior, and Monopoly Deal.
	</p>

	<p>The character first appeared on Chance and Community Chest cards in U.S. editions of Monopoly in 1936. The identity of the artist who designed the character has remained a mystery. Historian and author Philip Orbanes wrote in 2004 that it is believed that the character is based on either the calling cards of Albert Edward Richardson (Parker Brothers' first traveling salesman), the character of "Little Esky" from Esquire magazine, or a combination of the two. Orbanes later wrote, in 2006, that the character was also partially influenced by the stature and dress of financier and banker J. P. Morgan.
	</p>

	<p>He was named as the sixth richest fictional character in the 2006 Forbes Fictional 15 list on its website and the ninth richest in 2011.
	</p>
	
	<div id="spaces">
		<% @spaces.each do |space| %>
			<h4><%= space.name %>: <%= space.cost %></h4>
		<% end %>
	</div>
	
	<div id="social">
		<a href="https://facebook.com" target="_blank">
			<%= image_tag "social-facebook.png", alt: "Facebook icon" %>
		</a>
		<a href="http://flickr.com" target="_blank">
			<%= image_tag "social-flickr.png", alt: "Flickr icon" %>
		</a>
		<a href="https://foursquare.com" target="_blank">
			<%= image_tag "social-foursquare.png", alt: "Foursquare icon" %>
		</a>
		<a href="https://twitter.com" target="_blank">
			<%= image_tag "social-twitter.png", alt: "Twitter icon" %>
		</a>	
	</div>
</div>

moneybags/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mr.Monopoly</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

moneybags/app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.number_field :cost %>
  </div>
   <div class="field">
    <%= f.label :occupied %><br>
    <%= f.check_box :occupied %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

moneybags/app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

moneybags/app/views/spaces/index.html.erb
<h1>Listing spaces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spaces.each do |space| %>
  <tr>
    <td><%= space.name %></td>
    <td><%= space.cost %></td>
    <td><%= link_to 'Show', space %></td>
    <td><%= link_to 'Edit', edit_space_path(space) %></td>
    <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Space', new_space_path %>

moneybags/app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

moneybags/app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @space.name %>
</p>

<p>
  <b>Cost:</b>
  <%= @space.cost %>
</p>


<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>